## 회귀계수 구하기

- input: data_x(독립변수 행렬 데이터), data_y(종속변수 벡터 데이터)
- output: 추정된 회귀계수(벡터)

In [11]:
import numpy as np
from numpy.linalg import inv #역행렬 연산

In [20]:
# 회귀계수를 연산하는 함수

def estimate_beta(x, y):
    beta_hat = np.matmul(np.matmul(inv(np.matmul(np.transpose(x), x)),np.transpose(x)),y)
    
    return beta_hat

In [12]:
# 직접 연산하는 경우 x행렬에 intercept를 추가해야 함

x = np.array([ [1, 0, 1],
               [1, 2, 3],
               [1, 3, 8]]) #3x3

y = np.transpose(np.array([1, 3, 7])) #3x1

In [21]:
# 연산 대상인 행렬 확인

x, y

(array([[1, 0, 1],
        [1, 2, 3],
        [1, 3, 8]]), array([1, 3, 7]))

In [15]:
# 함수 결과값 확인
estimate_beta(x,y)

array([0.25, 0.25, 0.75])

### sklearn의 패키지 사용 결과와 비교

In [17]:
# 필요한 패키지 import

from sklearn.linear_model import LinearRegression

In [22]:
# sklearn은 디폴트로 intercept가 fit되므로, 데이터에 intercept가 포함된 경우는 fit_intercept=False로 해야함

reg = LinearRegression(fit_intercept=False).fit(x, y)

In [23]:
reg.coef_

array([0.25, 0.25, 0.75])